services:

  # Use postgres/example as user/password credentials
  db:
    container_name: test-db
    image: postgres:17.5
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      # localeを設定したい理由がないので、localeを設定しない (localeをCに設定する)
      # postgresql.org/docs/17/locale.html 23.1.2. Behavior
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - development-network

  db-management-client:
    # データベース操作が可能なWeb UIを提供するimage
    image: dpage/pgadmin4:9.6.0
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@test.com
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - development-network
    depends_on:
      - db

volumes:
  database:
    driver: local

networks:
  development-network: